/* tslint:disable */
/* eslint-disable */
/**
 * Sapie API
 * API documentation for the Sapie knowledge management application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AuthControllerGetCurrentUser401Response
 */
export interface AuthControllerGetCurrentUser401Response {
    /**
     * 
     * @type {number}
     * @memberof AuthControllerGetCurrentUser401Response
     */
    'statusCode'?: number;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerGetCurrentUser401Response
     */
    'message'?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthControllerGetCurrentUser401Response
     */
    'error'?: string;
}
/**
 * 
 * @export
 * @interface AuthenticatedUser
 */
export interface AuthenticatedUser {
    /**
     * Unique user identifier
     * @type {string}
     * @memberof AuthenticatedUser
     */
    'uid': string;
    /**
     * User email address
     * @type {string}
     * @memberof AuthenticatedUser
     */
    'email'?: string;
    /**
     * User display name
     * @type {string}
     * @memberof AuthenticatedUser
     */
    'displayName'?: string;
    /**
     * User profile photo URL
     * @type {string}
     * @memberof AuthenticatedUser
     */
    'photoURL'?: string;
    /**
     * Whether the user email is verified
     * @type {boolean}
     * @memberof AuthenticatedUser
     */
    'emailVerified': boolean;
    /**
     * Authentication provider information
     * @type {Array<ProviderDataDto>}
     * @memberof AuthenticatedUser
     */
    'providerData': Array<ProviderDataDto>;
    /**
     * Custom claims assigned to the user
     * @type {object}
     * @memberof AuthenticatedUser
     */
    'customClaims'?: object;
}
/**
 * 
 * @export
 * @interface ContentBodySummaryResponse
 */
export interface ContentBodySummaryResponse {
    /**
     * IANA media type of the stored body from the last successful `PUT …/body` (e.g. `text/plain`, `image/png`).
     * @type {string}
     * @memberof ContentBodySummaryResponse
     */
    'mimeType': string;
    /**
     * Byte size of the stored body after the last `PUT …/body`.
     * @type {number}
     * @memberof ContentBodySummaryResponse
     */
    'size': number;
    /**
     * When the body object was first written for this note.
     * @type {string}
     * @memberof ContentBodySummaryResponse
     */
    'createdAt': string;
    /**
     * When the body bytes last changed. Clients use this (not top-level `updatedAt`) to decide whether to re-download body bytes.
     * @type {string}
     * @memberof ContentBodySummaryResponse
     */
    'updatedAt': string;
}
/**
 * 
 * @export
 * @interface ContentBodyUrlResponse
 */
export interface ContentBodyUrlResponse {
    /**
     * Short-lived HTTPS URL to download the content body object from Cloud Storage
     * @type {string}
     * @memberof ContentBodyUrlResponse
     */
    'signedUrl': string;
    /**
     * ISO-8601 instant when signedUrl expires
     * @type {string}
     * @memberof ContentBodyUrlResponse
     */
    'expiresAt': string;
}
/**
 * 
 * @export
 * @interface ContentControllerPostBlob201Response
 */
export interface ContentControllerPostBlob201Response {
    /**
     * 
     * @type {string}
     * @memberof ContentControllerPostBlob201Response
     */
    'blobId'?: string;
    /**
     * 
     * @type {string}
     * @memberof ContentControllerPostBlob201Response
     */
    'url'?: string;
}
/**
 * 
 * @export
 * @interface ContentResponse
 */
export interface ContentResponse {
    /**
     * Unique identifier for the content (metadata)
     * @type {string}
     * @memberof ContentResponse
     */
    'id': string;
    /**
     * Display name of the content
     * @type {string}
     * @memberof ContentResponse
     */
    'name': string;
    /**
     * Type of content
     * @type {string}
     * @memberof ContentResponse
     */
    'type': ContentResponseTypeEnum;
    /**
     * ID of the parent directory, null for root directory
     * @type {string}
     * @memberof ContentResponse
     */
    'parentId': string | null;
    /**
     * Denormalized folder ID (set for deck-type content, enables folder-level study queries).
     * @type {string}
     * @memberof ContentResponse
     */
    'folderId'?: string | null;
    /**
     * ID of the user who owns this content
     * @type {string}
     * @memberof ContentResponse
     */
    'ownerId': string;
    /**
     * **Notes.** Public summary of the stored body. Omitted for directories. `null` before the first `PUT …/body`.
     * @type {ContentBodySummaryResponse}
     * @memberof ContentResponse
     */
    'body'?: ContentBodySummaryResponse | null;
    /**
     * Timestamp when the content was created
     * @type {string}
     * @memberof ContentResponse
     */
    'createdAt': string;
    /**
     * Timestamp when content metadata last changed (e.g. rename). Distinct from `body.updatedAt`, which tracks body bytes.
     * @type {string}
     * @memberof ContentResponse
     */
    'updatedAt': string;
}

export const ContentResponseTypeEnum = {
    Directory: 'directory',
    Note: 'note',
    Deck: 'deck'
} as const;

export type ContentResponseTypeEnum = typeof ContentResponseTypeEnum[keyof typeof ContentResponseTypeEnum];

/**
 * 
 * @export
 * @interface CreateContentRequest
 */
export interface CreateContentRequest {
    /**
     * Display name (1–200 chars). Spaces allowed. Cannot contain \\ / : * ? \" < > | or control characters.
     * @type {string}
     * @memberof CreateContentRequest
     */
    'name': string;
    /**
     * ID of the parent directory
     * @type {string}
     * @memberof CreateContentRequest
     */
    'parentId': string;
    /**
     * Kind of content to create. Omit or `note` for a note under a folder; `directory` for a folder under a folder.
     * @type {string}
     * @memberof CreateContentRequest
     */
    'type'?: CreateContentRequestTypeEnum;
}

export const CreateContentRequestTypeEnum = {
    Directory: 'directory',
    Note: 'note',
    Deck: 'deck'
} as const;

export type CreateContentRequestTypeEnum = typeof CreateContentRequestTypeEnum[keyof typeof CreateContentRequestTypeEnum];

/**
 * 
 * @export
 * @interface HealthControllerGetHealth200Response
 */
export interface HealthControllerGetHealth200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthControllerGetHealth200Response
     */
    'status'?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthControllerGetHealth200Response
     */
    'timestamp'?: string;
    /**
     * 
     * @type {string}
     * @memberof HealthControllerGetHealth200Response
     */
    'environment'?: string;
}
/**
 * 
 * @export
 * @interface ProblemDetailsDto
 */
export interface ProblemDetailsDto {
    /**
     * URI reference that identifies the problem type
     * @type {string}
     * @memberof ProblemDetailsDto
     */
    'type': string;
    /**
     * Short, human-readable summary of the problem type
     * @type {string}
     * @memberof ProblemDetailsDto
     */
    'title': string;
    /**
     * HTTP status code
     * @type {number}
     * @memberof ProblemDetailsDto
     */
    'status': number;
    /**
     * Human-readable explanation specific to this occurrence
     * @type {string}
     * @memberof ProblemDetailsDto
     */
    'detail': string;
    /**
     * URI reference identifying this specific occurrence (e.g. request path). Omitted when not available, such as before a resource identifier exists.
     * @type {string}
     * @memberof ProblemDetailsDto
     */
    'instance'?: string;
    /**
     * Per-field validation failures (extension member)
     * @type {Array<ProblemDetailsErrorItemDto>}
     * @memberof ProblemDetailsDto
     */
    'errors'?: Array<ProblemDetailsErrorItemDto>;
}
/**
 * 
 * @export
 * @interface ProblemDetailsErrorItemDto
 */
export interface ProblemDetailsErrorItemDto {
    /**
     * JSON Pointer to the invalid value
     * @type {string}
     * @memberof ProblemDetailsErrorItemDto
     */
    'path': string;
    /**
     * Human-readable messages for this pointer
     * @type {Array<string>}
     * @memberof ProblemDetailsErrorItemDto
     */
    'messages': Array<string>;
}
/**
 * 
 * @export
 * @interface ProviderDataDto
 */
export interface ProviderDataDto {
    /**
     * Authentication provider identifier
     * @type {string}
     * @memberof ProviderDataDto
     */
    'providerId': string;
}
/**
 * 
 * @export
 * @interface UpdateContentRequest
 */
export interface UpdateContentRequest {
    /**
     * New display name (1–200 chars). Spaces allowed. Cannot contain \\ / : * ? \" < > | or control characters. Omit the property when only changing other fields (e.g. future `parentId` moves); do not send `null`.
     * @type {string}
     * @memberof UpdateContentRequest
     */
    'name'?: string;
    /**
     * Target parent folder id after a move/reparent. **Not implemented yet** — the API returns `400 Bad Request` if this property is present (including `null`).
     * @type {string}
     * @memberof UpdateContentRequest
     */
    'parentId'?: string | null;
}

/**
 * AppApi - axios parameter creator
 * @export
 */
export const AppApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get API status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AppApi - functional programming interface
 * @export
 */
export const AppApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AppApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get API status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async appControllerGetHello(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.appControllerGetHello(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AppApi.appControllerGetHello']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AppApi - factory interface
 * @export
 */
export const AppApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AppApiFp(configuration)
    return {
        /**
         * 
         * @summary Get API status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.appControllerGetHello(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AppApi - interface
 * @export
 * @interface AppApi
 */
export interface AppApiInterface {
    /**
     * 
     * @summary Get API status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApiInterface
     */
    appControllerGetHello(options?: RawAxiosRequestConfig): AxiosPromise<string>;

}

/**
 * AppApi - object-oriented interface
 * @export
 * @class AppApi
 * @extends {BaseAPI}
 */
export class AppApi extends BaseAPI implements AppApiInterface {
    /**
     * 
     * @summary Get API status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AppApi
     */
    public appControllerGetHello(options?: RawAxiosRequestConfig) {
        return AppApiFp(this.configuration).appControllerGetHello(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * AuthenticationApi - axios parameter creator
 * @export
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns detailed information about the currently authenticated user from Firebase Auth
         * @summary Get current user information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerGetCurrentUser: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 * @export
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns detailed information about the currently authenticated user from Firebase Auth
         * @summary Get current user information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authControllerGetCurrentUser(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthenticatedUser>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authControllerGetCurrentUser(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.authControllerGetCurrentUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 * @export
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * Returns detailed information about the currently authenticated user from Firebase Auth
         * @summary Get current user information
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authControllerGetCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<AuthenticatedUser> {
            return localVarFp.authControllerGetCurrentUser(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - interface
 * @export
 * @interface AuthenticationApi
 */
export interface AuthenticationApiInterface {
    /**
     * Returns detailed information about the currently authenticated user from Firebase Auth
     * @summary Get current user information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApiInterface
     */
    authControllerGetCurrentUser(options?: RawAxiosRequestConfig): AxiosPromise<AuthenticatedUser>;

}

/**
 * AuthenticationApi - object-oriented interface
 * @export
 * @class AuthenticationApi
 * @extends {BaseAPI}
 */
export class AuthenticationApi extends BaseAPI implements AuthenticationApiInterface {
    /**
     * Returns detailed information about the currently authenticated user from Firebase Auth
     * @summary Get current user information
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthenticationApi
     */
    public authControllerGetCurrentUser(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).authControllerGetCurrentUser(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ContentApi - axios parameter creator
 * @export
 */
export const ContentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates metadata under the given parent. Default `type` is `note`. Send `type: directory` to create a folder (parent must be a folder).
         * @summary Create content (note or folder)
         * @param {CreateContentRequest} createContentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerCreateContent: async (createContentRequest: CreateContentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createContentRequest' is not null or undefined
            assertParamExists('contentControllerCreateContent', 'createContentRequest', createContentRequest)
            const localVarPath = `/api/content`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createContentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Soft-deletes content by setting `deleted: true`. Notes with content children (e.g. flashcard decks) require `?cascade=true` to delete. Folders are always cascaded to all descendants. Cloud Storage objects (bodies and blobs) are NOT deleted — permanent cleanup is deferred.
         * @summary Soft-delete content (note or directory)
         * @param {string} id 
         * @param {boolean} [cascade] Set to true to cascade-delete content children of a note.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerDeleteContent: async (id: string, cascade?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerDeleteContent', 'id', id)
            const localVarPath = `/api/content/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (cascade !== undefined) {
                localVarQueryParameter['cascade'] = cascade;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Stream blob bytes
         * @param {string} contentId Parent note ID
         * @param {string} blobId Blob ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetBlob: async (contentId: string, blobId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentId' is not null or undefined
            assertParamExists('contentControllerGetBlob', 'contentId', contentId)
            // verify required parameter 'blobId' is not null or undefined
            assertParamExists('contentControllerGetBlob', 'blobId', blobId)
            const localVarPath = `/api/content/{contentId}/blobs/{blobId}`
                .replace(`{${"contentId"}}`, encodeURIComponent(String(contentId)))
                .replace(`{${"blobId"}}`, encodeURIComponent(String(blobId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Authenticated read of stored body bytes (note markdown or image). Returns 200 with `Content-Type` from stored metadata. 404 when the content has no body yet. No ETag / 304 in this release.
         * @summary Stream content body bytes
         * @param {string} id The ID of the content whose body is read.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetContentBody: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerGetContentBody', 'id', id)
            const localVarPath = `/api/content/{id}/body`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns a short-lived signed URL for downloading the content body from Cloud Storage (valid 10 minutes). 404 when the content has no content body yet (client may treat as empty). `GET /:id` returns metadata only and never includes body bytes. 
         * @summary Get signed URL to read content body
         * @param {string} id The ID of the content whose content body is read (leaf types such as a note in MVP).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetContentBodySignedUrl: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerGetContentBodySignedUrl', 'id', id)
            const localVarPath = `/api/content/{id}/body/signed-url`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns Firestore metadata for the content (e.g. directory or note). Does not include the content body; use `GET …/body/signed-url` for a signed read URL. Directory items omit `body`; notes include `body: null` until the first `PUT …/body`, then a public summary (no storage URI).
         * @summary Get content by ID
         * @param {string} id The ID of the content.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetContentById: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerGetContentById', 'id', id)
            const localVarPath = `/api/content/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the authenticated user\'s root directory (\"My Contents\"). If the directory doesn\'t exist, it will be automatically created. This is the entry point for all content management operations.
         * @summary Get or create user\'s root directory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetRootDirectory: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/content/root`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns child content (metadata only) for the given parent ID. Returns **folders and notes** for sidebar tree use. Does not load content bodies or signed read URLs.
         * @summary List a parent\'s children
         * @param {string} id The ID of the parent content.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerListContents: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerListContents', 'id', id)
            const localVarPath = `/api/content/{id}/children`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Partially updates content metadata. Today this supports renaming (`name`). Moving an item to another folder (`parentId`) will use the same route; that behavior is **not implemented yet** and returns `400 Bad Request` if `parentId` is sent. Body bytes and the nested `body` summary are changed only via `PUT …/body`. When renaming, names must stay unique among siblings under the same parent.
         * @summary Patch content metadata
         * @param {string} id The ID of the content.
         * @param {UpdateContentRequest} updateContentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerPatchContent: async (id: string, updateContentRequest: UpdateContentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerPatchContent', 'id', id)
            // verify required parameter 'updateContentRequest' is not null or undefined
            assertParamExists('contentControllerPatchContent', 'updateContentRequest', updateContentRequest)
            const localVarPath = `/api/content/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateContentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Stores raw bytes as a blob under the note. Returns the generated blob ID and its read URL.
         * @summary Upload a blob (inline image) for a note
         * @param {string} contentId Parent note ID
         * @param {string} contentType 
         * @param {File} body Raw bytes of the blob (inline image). The &#x60;Content-Type&#x60; header sets the stored media type.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerPostBlob: async (contentId: string, contentType: string, body: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'contentId' is not null or undefined
            assertParamExists('contentControllerPostBlob', 'contentId', contentId)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('contentControllerPostBlob', 'contentType', contentType)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('contentControllerPostBlob', 'body', body)
            const localVarPath = `/api/content/{contentId}/blobs`
                .replace(`{${"contentId"}}`, encodeURIComponent(String(contentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'image/png';

            if (contentType != null) {
                localVarHeaderParameter['content-type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Single endpoint for note markdown body bytes. Updates Cloud Storage and nested Firestore `body` (incl. `body.updatedAt`). **Notes** require `expectedRevision` query parameter (`body.updatedAt` ISO string from metadata, or empty string before first save). Returns **409** when revision is stale.
         * @summary Upload or replace content body
         * @param {string} id The ID of the content whose content body is replaced (leaf types such as a note in MVP).
         * @param {string} contentType 
         * @param {File} body Raw bytes of the content body. The &#x60;Content-Type&#x60; header sets the stored media type (e.g. markdown as &#x60;text/plain&#x60; or &#x60;text/markdown&#x60;, images as &#x60;image/_*&#x60;). Omitting &#x60;Content-Type&#x60; defaults to &#x60;application/octet-stream&#x60;. &#x60;multipart/_*&#x60; is rejected (415) until explicitly supported.
         * @param {string} [expectedRevision] Required for notes. &#x60;body.updatedAt&#x60; ISO string at load/last save, or empty string when the note has no body yet.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerPutContentBody: async (id: string, contentType: string, body: File, expectedRevision?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('contentControllerPutContentBody', 'id', id)
            // verify required parameter 'contentType' is not null or undefined
            assertParamExists('contentControllerPutContentBody', 'contentType', contentType)
            // verify required parameter 'body' is not null or undefined
            assertParamExists('contentControllerPutContentBody', 'body', body)
            const localVarPath = `/api/content/{id}/body`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (expectedRevision !== undefined) {
                localVarQueryParameter['expectedRevision'] = expectedRevision;
            }


    
            localVarHeaderParameter['Content-Type'] = 'application/octet-stream';

            if (contentType != null) {
                localVarHeaderParameter['content-type'] = String(contentType);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ContentApi - functional programming interface
 * @export
 */
export const ContentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ContentApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates metadata under the given parent. Default `type` is `note`. Send `type: directory` to create a folder (parent must be a folder).
         * @summary Create content (note or folder)
         * @param {CreateContentRequest} createContentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerCreateContent(createContentRequest: CreateContentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerCreateContent(createContentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerCreateContent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Soft-deletes content by setting `deleted: true`. Notes with content children (e.g. flashcard decks) require `?cascade=true` to delete. Folders are always cascaded to all descendants. Cloud Storage objects (bodies and blobs) are NOT deleted — permanent cleanup is deferred.
         * @summary Soft-delete content (note or directory)
         * @param {string} id 
         * @param {boolean} [cascade] Set to true to cascade-delete content children of a note.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerDeleteContent(id: string, cascade?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerDeleteContent(id, cascade, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerDeleteContent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Stream blob bytes
         * @param {string} contentId Parent note ID
         * @param {string} blobId Blob ID
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerGetBlob(contentId: string, blobId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerGetBlob(contentId, blobId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerGetBlob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Authenticated read of stored body bytes (note markdown or image). Returns 200 with `Content-Type` from stored metadata. 404 when the content has no body yet. No ETag / 304 in this release.
         * @summary Stream content body bytes
         * @param {string} id The ID of the content whose body is read.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerGetContentBody(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerGetContentBody(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerGetContentBody']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns a short-lived signed URL for downloading the content body from Cloud Storage (valid 10 minutes). 404 when the content has no content body yet (client may treat as empty). `GET /:id` returns metadata only and never includes body bytes. 
         * @summary Get signed URL to read content body
         * @param {string} id The ID of the content whose content body is read (leaf types such as a note in MVP).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerGetContentBodySignedUrl(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentBodyUrlResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerGetContentBodySignedUrl(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerGetContentBodySignedUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns Firestore metadata for the content (e.g. directory or note). Does not include the content body; use `GET …/body/signed-url` for a signed read URL. Directory items omit `body`; notes include `body: null` until the first `PUT …/body`, then a public summary (no storage URI).
         * @summary Get content by ID
         * @param {string} id The ID of the content.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerGetContentById(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerGetContentById(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerGetContentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the authenticated user\'s root directory (\"My Contents\"). If the directory doesn\'t exist, it will be automatically created. This is the entry point for all content management operations.
         * @summary Get or create user\'s root directory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerGetRootDirectory(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerGetRootDirectory(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerGetRootDirectory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns child content (metadata only) for the given parent ID. Returns **folders and notes** for sidebar tree use. Does not load content bodies or signed read URLs.
         * @summary List a parent\'s children
         * @param {string} id The ID of the parent content.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerListContents(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ContentResponse>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerListContents(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerListContents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Partially updates content metadata. Today this supports renaming (`name`). Moving an item to another folder (`parentId`) will use the same route; that behavior is **not implemented yet** and returns `400 Bad Request` if `parentId` is sent. Body bytes and the nested `body` summary are changed only via `PUT …/body`. When renaming, names must stay unique among siblings under the same parent.
         * @summary Patch content metadata
         * @param {string} id The ID of the content.
         * @param {UpdateContentRequest} updateContentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerPatchContent(id: string, updateContentRequest: UpdateContentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerPatchContent(id, updateContentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerPatchContent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Stores raw bytes as a blob under the note. Returns the generated blob ID and its read URL.
         * @summary Upload a blob (inline image) for a note
         * @param {string} contentId Parent note ID
         * @param {string} contentType 
         * @param {File} body Raw bytes of the blob (inline image). The &#x60;Content-Type&#x60; header sets the stored media type.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerPostBlob(contentId: string, contentType: string, body: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentControllerPostBlob201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerPostBlob(contentId, contentType, body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerPostBlob']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Single endpoint for note markdown body bytes. Updates Cloud Storage and nested Firestore `body` (incl. `body.updatedAt`). **Notes** require `expectedRevision` query parameter (`body.updatedAt` ISO string from metadata, or empty string before first save). Returns **409** when revision is stale.
         * @summary Upload or replace content body
         * @param {string} id The ID of the content whose content body is replaced (leaf types such as a note in MVP).
         * @param {string} contentType 
         * @param {File} body Raw bytes of the content body. The &#x60;Content-Type&#x60; header sets the stored media type (e.g. markdown as &#x60;text/plain&#x60; or &#x60;text/markdown&#x60;, images as &#x60;image/_*&#x60;). Omitting &#x60;Content-Type&#x60; defaults to &#x60;application/octet-stream&#x60;. &#x60;multipart/_*&#x60; is rejected (415) until explicitly supported.
         * @param {string} [expectedRevision] Required for notes. &#x60;body.updatedAt&#x60; ISO string at load/last save, or empty string when the note has no body yet.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async contentControllerPutContentBody(id: string, contentType: string, body: File, expectedRevision?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ContentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.contentControllerPutContentBody(id, contentType, body, expectedRevision, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ContentApi.contentControllerPutContentBody']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ContentApi - factory interface
 * @export
 */
export const ContentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ContentApiFp(configuration)
    return {
        /**
         * Creates metadata under the given parent. Default `type` is `note`. Send `type: directory` to create a folder (parent must be a folder).
         * @summary Create content (note or folder)
         * @param {ContentApiContentControllerCreateContentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerCreateContent(requestParameters: ContentApiContentControllerCreateContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse> {
            return localVarFp.contentControllerCreateContent(requestParameters.createContentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Soft-deletes content by setting `deleted: true`. Notes with content children (e.g. flashcard decks) require `?cascade=true` to delete. Folders are always cascaded to all descendants. Cloud Storage objects (bodies and blobs) are NOT deleted — permanent cleanup is deferred.
         * @summary Soft-delete content (note or directory)
         * @param {ContentApiContentControllerDeleteContentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerDeleteContent(requestParameters: ContentApiContentControllerDeleteContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.contentControllerDeleteContent(requestParameters.id, requestParameters.cascade, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Stream blob bytes
         * @param {ContentApiContentControllerGetBlobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetBlob(requestParameters: ContentApiContentControllerGetBlobRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.contentControllerGetBlob(requestParameters.contentId, requestParameters.blobId, options).then((request) => request(axios, basePath));
        },
        /**
         * Authenticated read of stored body bytes (note markdown or image). Returns 200 with `Content-Type` from stored metadata. 404 when the content has no body yet. No ETag / 304 in this release.
         * @summary Stream content body bytes
         * @param {ContentApiContentControllerGetContentBodyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetContentBody(requestParameters: ContentApiContentControllerGetContentBodyRequest, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.contentControllerGetContentBody(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns a short-lived signed URL for downloading the content body from Cloud Storage (valid 10 minutes). 404 when the content has no content body yet (client may treat as empty). `GET /:id` returns metadata only and never includes body bytes. 
         * @summary Get signed URL to read content body
         * @param {ContentApiContentControllerGetContentBodySignedUrlRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetContentBodySignedUrl(requestParameters: ContentApiContentControllerGetContentBodySignedUrlRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentBodyUrlResponse> {
            return localVarFp.contentControllerGetContentBodySignedUrl(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns Firestore metadata for the content (e.g. directory or note). Does not include the content body; use `GET …/body/signed-url` for a signed read URL. Directory items omit `body`; notes include `body: null` until the first `PUT …/body`, then a public summary (no storage URI).
         * @summary Get content by ID
         * @param {ContentApiContentControllerGetContentByIdRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetContentById(requestParameters: ContentApiContentControllerGetContentByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse> {
            return localVarFp.contentControllerGetContentById(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the authenticated user\'s root directory (\"My Contents\"). If the directory doesn\'t exist, it will be automatically created. This is the entry point for all content management operations.
         * @summary Get or create user\'s root directory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerGetRootDirectory(options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse> {
            return localVarFp.contentControllerGetRootDirectory(options).then((request) => request(axios, basePath));
        },
        /**
         * Returns child content (metadata only) for the given parent ID. Returns **folders and notes** for sidebar tree use. Does not load content bodies or signed read URLs.
         * @summary List a parent\'s children
         * @param {ContentApiContentControllerListContentsRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerListContents(requestParameters: ContentApiContentControllerListContentsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContentResponse>> {
            return localVarFp.contentControllerListContents(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * Partially updates content metadata. Today this supports renaming (`name`). Moving an item to another folder (`parentId`) will use the same route; that behavior is **not implemented yet** and returns `400 Bad Request` if `parentId` is sent. Body bytes and the nested `body` summary are changed only via `PUT …/body`. When renaming, names must stay unique among siblings under the same parent.
         * @summary Patch content metadata
         * @param {ContentApiContentControllerPatchContentRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerPatchContent(requestParameters: ContentApiContentControllerPatchContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse> {
            return localVarFp.contentControllerPatchContent(requestParameters.id, requestParameters.updateContentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Stores raw bytes as a blob under the note. Returns the generated blob ID and its read URL.
         * @summary Upload a blob (inline image) for a note
         * @param {ContentApiContentControllerPostBlobRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerPostBlob(requestParameters: ContentApiContentControllerPostBlobRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentControllerPostBlob201Response> {
            return localVarFp.contentControllerPostBlob(requestParameters.contentId, requestParameters.contentType, requestParameters.body, options).then((request) => request(axios, basePath));
        },
        /**
         * Single endpoint for note markdown body bytes. Updates Cloud Storage and nested Firestore `body` (incl. `body.updatedAt`). **Notes** require `expectedRevision` query parameter (`body.updatedAt` ISO string from metadata, or empty string before first save). Returns **409** when revision is stale.
         * @summary Upload or replace content body
         * @param {ContentApiContentControllerPutContentBodyRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        contentControllerPutContentBody(requestParameters: ContentApiContentControllerPutContentBodyRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse> {
            return localVarFp.contentControllerPutContentBody(requestParameters.id, requestParameters.contentType, requestParameters.body, requestParameters.expectedRevision, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ContentApi - interface
 * @export
 * @interface ContentApi
 */
export interface ContentApiInterface {
    /**
     * Creates metadata under the given parent. Default `type` is `note`. Send `type: directory` to create a folder (parent must be a folder).
     * @summary Create content (note or folder)
     * @param {ContentApiContentControllerCreateContentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerCreateContent(requestParameters: ContentApiContentControllerCreateContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse>;

    /**
     * Soft-deletes content by setting `deleted: true`. Notes with content children (e.g. flashcard decks) require `?cascade=true` to delete. Folders are always cascaded to all descendants. Cloud Storage objects (bodies and blobs) are NOT deleted — permanent cleanup is deferred.
     * @summary Soft-delete content (note or directory)
     * @param {ContentApiContentControllerDeleteContentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerDeleteContent(requestParameters: ContentApiContentControllerDeleteContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Stream blob bytes
     * @param {ContentApiContentControllerGetBlobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerGetBlob(requestParameters: ContentApiContentControllerGetBlobRequest, options?: RawAxiosRequestConfig): AxiosPromise<File>;

    /**
     * Authenticated read of stored body bytes (note markdown or image). Returns 200 with `Content-Type` from stored metadata. 404 when the content has no body yet. No ETag / 304 in this release.
     * @summary Stream content body bytes
     * @param {ContentApiContentControllerGetContentBodyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerGetContentBody(requestParameters: ContentApiContentControllerGetContentBodyRequest, options?: RawAxiosRequestConfig): AxiosPromise<File>;

    /**
     * Returns a short-lived signed URL for downloading the content body from Cloud Storage (valid 10 minutes). 404 when the content has no content body yet (client may treat as empty). `GET /:id` returns metadata only and never includes body bytes. 
     * @summary Get signed URL to read content body
     * @param {ContentApiContentControllerGetContentBodySignedUrlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerGetContentBodySignedUrl(requestParameters: ContentApiContentControllerGetContentBodySignedUrlRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentBodyUrlResponse>;

    /**
     * Returns Firestore metadata for the content (e.g. directory or note). Does not include the content body; use `GET …/body/signed-url` for a signed read URL. Directory items omit `body`; notes include `body: null` until the first `PUT …/body`, then a public summary (no storage URI).
     * @summary Get content by ID
     * @param {ContentApiContentControllerGetContentByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerGetContentById(requestParameters: ContentApiContentControllerGetContentByIdRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse>;

    /**
     * Returns the authenticated user\'s root directory (\"My Contents\"). If the directory doesn\'t exist, it will be automatically created. This is the entry point for all content management operations.
     * @summary Get or create user\'s root directory
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerGetRootDirectory(options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse>;

    /**
     * Returns child content (metadata only) for the given parent ID. Returns **folders and notes** for sidebar tree use. Does not load content bodies or signed read URLs.
     * @summary List a parent\'s children
     * @param {ContentApiContentControllerListContentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerListContents(requestParameters: ContentApiContentControllerListContentsRequest, options?: RawAxiosRequestConfig): AxiosPromise<Array<ContentResponse>>;

    /**
     * Partially updates content metadata. Today this supports renaming (`name`). Moving an item to another folder (`parentId`) will use the same route; that behavior is **not implemented yet** and returns `400 Bad Request` if `parentId` is sent. Body bytes and the nested `body` summary are changed only via `PUT …/body`. When renaming, names must stay unique among siblings under the same parent.
     * @summary Patch content metadata
     * @param {ContentApiContentControllerPatchContentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerPatchContent(requestParameters: ContentApiContentControllerPatchContentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse>;

    /**
     * Stores raw bytes as a blob under the note. Returns the generated blob ID and its read URL.
     * @summary Upload a blob (inline image) for a note
     * @param {ContentApiContentControllerPostBlobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerPostBlob(requestParameters: ContentApiContentControllerPostBlobRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentControllerPostBlob201Response>;

    /**
     * Single endpoint for note markdown body bytes. Updates Cloud Storage and nested Firestore `body` (incl. `body.updatedAt`). **Notes** require `expectedRevision` query parameter (`body.updatedAt` ISO string from metadata, or empty string before first save). Returns **409** when revision is stale.
     * @summary Upload or replace content body
     * @param {ContentApiContentControllerPutContentBodyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApiInterface
     */
    contentControllerPutContentBody(requestParameters: ContentApiContentControllerPutContentBodyRequest, options?: RawAxiosRequestConfig): AxiosPromise<ContentResponse>;

}

/**
 * Request parameters for contentControllerCreateContent operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerCreateContentRequest
 */
export interface ContentApiContentControllerCreateContentRequest {
    /**
     * 
     * @type {CreateContentRequest}
     * @memberof ContentApiContentControllerCreateContent
     */
    readonly createContentRequest: CreateContentRequest
}

/**
 * Request parameters for contentControllerDeleteContent operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerDeleteContentRequest
 */
export interface ContentApiContentControllerDeleteContentRequest {
    /**
     * 
     * @type {string}
     * @memberof ContentApiContentControllerDeleteContent
     */
    readonly id: string

    /**
     * Set to true to cascade-delete content children of a note.
     * @type {boolean}
     * @memberof ContentApiContentControllerDeleteContent
     */
    readonly cascade?: boolean
}

/**
 * Request parameters for contentControllerGetBlob operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerGetBlobRequest
 */
export interface ContentApiContentControllerGetBlobRequest {
    /**
     * Parent note ID
     * @type {string}
     * @memberof ContentApiContentControllerGetBlob
     */
    readonly contentId: string

    /**
     * Blob ID
     * @type {string}
     * @memberof ContentApiContentControllerGetBlob
     */
    readonly blobId: string
}

/**
 * Request parameters for contentControllerGetContentBody operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerGetContentBodyRequest
 */
export interface ContentApiContentControllerGetContentBodyRequest {
    /**
     * The ID of the content whose body is read.
     * @type {string}
     * @memberof ContentApiContentControllerGetContentBody
     */
    readonly id: string
}

/**
 * Request parameters for contentControllerGetContentBodySignedUrl operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerGetContentBodySignedUrlRequest
 */
export interface ContentApiContentControllerGetContentBodySignedUrlRequest {
    /**
     * The ID of the content whose content body is read (leaf types such as a note in MVP).
     * @type {string}
     * @memberof ContentApiContentControllerGetContentBodySignedUrl
     */
    readonly id: string
}

/**
 * Request parameters for contentControllerGetContentById operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerGetContentByIdRequest
 */
export interface ContentApiContentControllerGetContentByIdRequest {
    /**
     * The ID of the content.
     * @type {string}
     * @memberof ContentApiContentControllerGetContentById
     */
    readonly id: string
}

/**
 * Request parameters for contentControllerListContents operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerListContentsRequest
 */
export interface ContentApiContentControllerListContentsRequest {
    /**
     * The ID of the parent content.
     * @type {string}
     * @memberof ContentApiContentControllerListContents
     */
    readonly id: string
}

/**
 * Request parameters for contentControllerPatchContent operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerPatchContentRequest
 */
export interface ContentApiContentControllerPatchContentRequest {
    /**
     * The ID of the content.
     * @type {string}
     * @memberof ContentApiContentControllerPatchContent
     */
    readonly id: string

    /**
     * 
     * @type {UpdateContentRequest}
     * @memberof ContentApiContentControllerPatchContent
     */
    readonly updateContentRequest: UpdateContentRequest
}

/**
 * Request parameters for contentControllerPostBlob operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerPostBlobRequest
 */
export interface ContentApiContentControllerPostBlobRequest {
    /**
     * Parent note ID
     * @type {string}
     * @memberof ContentApiContentControllerPostBlob
     */
    readonly contentId: string

    /**
     * 
     * @type {string}
     * @memberof ContentApiContentControllerPostBlob
     */
    readonly contentType: string

    /**
     * Raw bytes of the blob (inline image). The &#x60;Content-Type&#x60; header sets the stored media type.
     * @type {File}
     * @memberof ContentApiContentControllerPostBlob
     */
    readonly body: File
}

/**
 * Request parameters for contentControllerPutContentBody operation in ContentApi.
 * @export
 * @interface ContentApiContentControllerPutContentBodyRequest
 */
export interface ContentApiContentControllerPutContentBodyRequest {
    /**
     * The ID of the content whose content body is replaced (leaf types such as a note in MVP).
     * @type {string}
     * @memberof ContentApiContentControllerPutContentBody
     */
    readonly id: string

    /**
     * 
     * @type {string}
     * @memberof ContentApiContentControllerPutContentBody
     */
    readonly contentType: string

    /**
     * Raw bytes of the content body. The &#x60;Content-Type&#x60; header sets the stored media type (e.g. markdown as &#x60;text/plain&#x60; or &#x60;text/markdown&#x60;, images as &#x60;image/_*&#x60;). Omitting &#x60;Content-Type&#x60; defaults to &#x60;application/octet-stream&#x60;. &#x60;multipart/_*&#x60; is rejected (415) until explicitly supported.
     * @type {File}
     * @memberof ContentApiContentControllerPutContentBody
     */
    readonly body: File

    /**
     * Required for notes. &#x60;body.updatedAt&#x60; ISO string at load/last save, or empty string when the note has no body yet.
     * @type {string}
     * @memberof ContentApiContentControllerPutContentBody
     */
    readonly expectedRevision?: string
}

/**
 * ContentApi - object-oriented interface
 * @export
 * @class ContentApi
 * @extends {BaseAPI}
 */
export class ContentApi extends BaseAPI implements ContentApiInterface {
    /**
     * Creates metadata under the given parent. Default `type` is `note`. Send `type: directory` to create a folder (parent must be a folder).
     * @summary Create content (note or folder)
     * @param {ContentApiContentControllerCreateContentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerCreateContent(requestParameters: ContentApiContentControllerCreateContentRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerCreateContent(requestParameters.createContentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Soft-deletes content by setting `deleted: true`. Notes with content children (e.g. flashcard decks) require `?cascade=true` to delete. Folders are always cascaded to all descendants. Cloud Storage objects (bodies and blobs) are NOT deleted — permanent cleanup is deferred.
     * @summary Soft-delete content (note or directory)
     * @param {ContentApiContentControllerDeleteContentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerDeleteContent(requestParameters: ContentApiContentControllerDeleteContentRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerDeleteContent(requestParameters.id, requestParameters.cascade, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Stream blob bytes
     * @param {ContentApiContentControllerGetBlobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerGetBlob(requestParameters: ContentApiContentControllerGetBlobRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerGetBlob(requestParameters.contentId, requestParameters.blobId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Authenticated read of stored body bytes (note markdown or image). Returns 200 with `Content-Type` from stored metadata. 404 when the content has no body yet. No ETag / 304 in this release.
     * @summary Stream content body bytes
     * @param {ContentApiContentControllerGetContentBodyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerGetContentBody(requestParameters: ContentApiContentControllerGetContentBodyRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerGetContentBody(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns a short-lived signed URL for downloading the content body from Cloud Storage (valid 10 minutes). 404 when the content has no content body yet (client may treat as empty). `GET /:id` returns metadata only and never includes body bytes. 
     * @summary Get signed URL to read content body
     * @param {ContentApiContentControllerGetContentBodySignedUrlRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerGetContentBodySignedUrl(requestParameters: ContentApiContentControllerGetContentBodySignedUrlRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerGetContentBodySignedUrl(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns Firestore metadata for the content (e.g. directory or note). Does not include the content body; use `GET …/body/signed-url` for a signed read URL. Directory items omit `body`; notes include `body: null` until the first `PUT …/body`, then a public summary (no storage URI).
     * @summary Get content by ID
     * @param {ContentApiContentControllerGetContentByIdRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerGetContentById(requestParameters: ContentApiContentControllerGetContentByIdRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerGetContentById(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the authenticated user\'s root directory (\"My Contents\"). If the directory doesn\'t exist, it will be automatically created. This is the entry point for all content management operations.
     * @summary Get or create user\'s root directory
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerGetRootDirectory(options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerGetRootDirectory(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns child content (metadata only) for the given parent ID. Returns **folders and notes** for sidebar tree use. Does not load content bodies or signed read URLs.
     * @summary List a parent\'s children
     * @param {ContentApiContentControllerListContentsRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerListContents(requestParameters: ContentApiContentControllerListContentsRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerListContents(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Partially updates content metadata. Today this supports renaming (`name`). Moving an item to another folder (`parentId`) will use the same route; that behavior is **not implemented yet** and returns `400 Bad Request` if `parentId` is sent. Body bytes and the nested `body` summary are changed only via `PUT …/body`. When renaming, names must stay unique among siblings under the same parent.
     * @summary Patch content metadata
     * @param {ContentApiContentControllerPatchContentRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerPatchContent(requestParameters: ContentApiContentControllerPatchContentRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerPatchContent(requestParameters.id, requestParameters.updateContentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Stores raw bytes as a blob under the note. Returns the generated blob ID and its read URL.
     * @summary Upload a blob (inline image) for a note
     * @param {ContentApiContentControllerPostBlobRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerPostBlob(requestParameters: ContentApiContentControllerPostBlobRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerPostBlob(requestParameters.contentId, requestParameters.contentType, requestParameters.body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Single endpoint for note markdown body bytes. Updates Cloud Storage and nested Firestore `body` (incl. `body.updatedAt`). **Notes** require `expectedRevision` query parameter (`body.updatedAt` ISO string from metadata, or empty string before first save). Returns **409** when revision is stale.
     * @summary Upload or replace content body
     * @param {ContentApiContentControllerPutContentBodyRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ContentApi
     */
    public contentControllerPutContentBody(requestParameters: ContentApiContentControllerPutContentBodyRequest, options?: RawAxiosRequestConfig) {
        return ContentApiFp(this.configuration).contentControllerPutContentBody(requestParameters.id, requestParameters.contentType, requestParameters.body, requestParameters.expectedRevision, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FakeStorageReadApi - axios parameter creator
 * @export
 */
export const FakeStorageReadApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fakeStorageReadControllerRead: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/fake-storage/read`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FakeStorageReadApi - functional programming interface
 * @export
 */
export const FakeStorageReadApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FakeStorageReadApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fakeStorageReadControllerRead(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fakeStorageReadControllerRead(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FakeStorageReadApi.fakeStorageReadControllerRead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FakeStorageReadApi - factory interface
 * @export
 */
export const FakeStorageReadApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FakeStorageReadApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fakeStorageReadControllerRead(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.fakeStorageReadControllerRead(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FakeStorageReadApi - interface
 * @export
 * @interface FakeStorageReadApi
 */
export interface FakeStorageReadApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FakeStorageReadApiInterface
     */
    fakeStorageReadControllerRead(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * FakeStorageReadApi - object-oriented interface
 * @export
 * @class FakeStorageReadApi
 * @extends {BaseAPI}
 */
export class FakeStorageReadApi extends BaseAPI implements FakeStorageReadApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FakeStorageReadApi
     */
    public fakeStorageReadControllerRead(options?: RawAxiosRequestConfig) {
        return FakeStorageReadApiFp(this.configuration).fakeStorageReadControllerRead(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/health`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthControllerGetHealth(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<HealthControllerGetHealth200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthControllerGetHealth(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthControllerGetHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @summary Health check endpoint
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthControllerGetHealth(options?: RawAxiosRequestConfig): AxiosPromise<HealthControllerGetHealth200Response> {
            return localVarFp.healthControllerGetHealth(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - interface
 * @export
 * @interface HealthApi
 */
export interface HealthApiInterface {
    /**
     * 
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthControllerGetHealth(options?: RawAxiosRequestConfig): AxiosPromise<HealthControllerGetHealth200Response>;

}

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI implements HealthApiInterface {
    /**
     * 
     * @summary Health check endpoint
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthControllerGetHealth(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthControllerGetHealth(options).then((request) => request(this.axios, this.basePath));
    }
}



