#!/usr/bin/env bash
# Manual QA test steps for the full Sapie app (API + web + CLI).
# Run these in order. Each step explains what to do and what to expect.
set -euo pipefail

echo "═══════════════════════════════════════════════════════════"
echo "  Sapie — Manual Test Plan"
echo "═══════════════════════════════════════════════════════════"
echo ""
echo "Prerequisites: Docker, Node.js 22+, pnpm"
echo ""

# ─── 1. Start the backend ───────────────────────────────────────────────
echo "STEP 1 — Start Firebase emulators and API server"
echo "─────────────────────────────────────────────────"
echo "  a) Start emulators:   bash scripts/emulator-dev-local-logs.sh"
echo "     (leave it running in a terminal)"
echo ""
echo "  b) Start API server:  cd packages/api && pnpm run start:dev"
echo "     (leave it running in another terminal, listens on :3000)"
echo ""
echo "  c) Verify:             curl http://localhost:3000/api/health"
echo "     Expected:           200 OK"
echo ""

# ─── 2. Start the web app ───────────────────────────────────────────────
echo "STEP 2 — Start the web app"
echo "──────────────────────────"
echo "  a) Start Vite dev:     cd packages/web && pnpm run dev"
echo "     (leave it running in another terminal)"
echo ""
echo "  b) Open browser:       http://localhost:5173"
echo ""
echo "  c) Log in:             Use the emulator UI (http://localhost:4002)"
echo "     to create a test user, then sign in with any email/password."
echo ""

# ─── 3. Seed test data ──────────────────────────────────────────────────
echo "STEP 3 — Seed the workspace with sample content"
echo "─────────────────────────────────────────────────"
echo "  a) Run seed script:    npx tsx scripts/seed-dev-data.ts"
echo ""
echo "  Expected output:"
echo "    Folders:  6"
echo "    Notes:    6"
echo "    Decks:    2 (Arrays, Sorting)"
echo "    Cards:    7 total"
echo ""
echo "  b) In the browser, the sidebar should show:"
echo "       📁 Computer Science"
echo "         📁 Data Structures"
echo "           📝 Arrays        (with 🃏 deck)"
echo "           📝 Linked Lists"
echo "         📁 Algorithms"
echo "           📝 Sorting       (with 🃏 deck)"
echo "           📝 Searching"
echo "         📁 System Design"
echo "           📝 Scalability"
echo "       📁 Mathematics"
echo "         📁 Linear Algebra"
echo "           📝 Matrices"
echo ""

# ─── 4. Note editor ─────────────────────────────────────────────────────
echo "STEP 4 — Test the note editor"
echo "───────────────────────────────"
echo "  a) Click 'Arrays' in the sidebar."
echo "     Expected: Markdown editor opens with DSA content."
echo ""
echo "  b) Type some text in the editor."
echo "     Expected: Auto-save indicator shows 'Saving...' → 'Saved'."
echo ""
echo "  c) Reload the page."
echo "     Expected: Changes persist."
echo ""
echo "  d) Rename the note via the editor header."
echo "     Expected: Sidebar updates with new name."
echo ""

# ─── 5. Folder management ───────────────────────────────────────────────
echo "STEP 5 — Test folder operations"
echo "─────────────────────────────────"
echo "  a) Right-click 'Data Structures' → 'New Folder'."
echo "     Expected: Modal appears. Create folder 'Graphs'."
echo "     Expected: Appears in the sidebar under Data Structures."
echo ""
echo "  b) Click the new folder."
echo "     Expected: Folder page shows name and tags."
echo ""
echo "  c) Add a tag: type 'dsa' and press Enter."
echo "     Expected: Tag chip appears below the folder name."
echo ""

# ─── 6. Flashcard decks & cards ─────────────────────────────────────────
echo "STEP 6 — Test flashcard decks and cards"
echo "─────────────────────────────────────────"
echo "  a) Click 'Arrays' in the sidebar."
echo "     Expected: The Attachments section at the bottom shows 'Arrays' deck."
echo ""
echo "  b) Click the deck name."
echo "     Expected: Deck view page with 3 cards listed."
echo ""
echo "  c) Click 'Add Card'."
echo "     Expected: Front/back form. Fill and submit."
echo "     Expected: New card appears in the list."
echo ""
echo "  d) Click 'Study' on the deck page."
echo "     Expected: Study mode — front side shown first."
echo ""

# ─── 7. Study mode ──────────────────────────────────────────────────────
echo "STEP 7 — Test study mode"
echo "──────────────────────────"
echo "  a) In study mode, read the question, then click to reveal answer."
echo ""
echo "  b) Click 'I know' or 'I don't know'."
echo "     Expected: Next card appears."
echo ""
echo "  c) Complete all cards."
echo "     Expected: Summary screen or navigation back."
echo ""
echo "  d) Go to Study Dashboard (top nav or '/' route)."
echo "     Expected: Shows content roots with due card counts."
echo ""
echo "  e) Right-click a folder in sidebar → 'Study all'."
echo "     Expected: All cards from all decks in that folder load."
echo ""

# ─── 8. CLI — local workspace copy (sync) ───────────────────────────────
echo "STEP 8 — Test CLI local workspace copy (pull/push)"
echo "────────────────────────────────────────────────────"
echo "  a) Build the CLI:      cd packages/cli && pnpm run build"
echo ""
echo "  b) Init workspace:"
echo "     mkdir -p /tmp/sapie-qa && cd /tmp/sapie-qa"
echo "     npx tsx ~/dev/joaopmafra/apps/knowledge-management/sapie/packages/cli/src/index.ts init"
echo "     Expected: Creates .sapie/ with config files."
echo ""
echo "  c) Configure CLI to use local emulator:"
echo "     Edit .sapie/config.json:"
echo "       apiBaseUrl: \"http://localhost:3000\""
echo ""
echo "  d) Log in:"
echo "     npx tsx …/src/index.ts login"
echo "     Expected: Opens browser for Firebase Auth, stores token."
echo ""
echo "  e) Pull content:"
echo "     npx tsx …/src/index.ts pull"
echo "     Expected: Downloads all notes, folders, decks to /tmp/sapie-qa/"
echo "               File structure matches the sidebar tree."
echo "               My Contents/Data Structures/Arrays.md/index.md"
echo "               My Contents/Data Structures/Arrays.md/decks/Arrays.json"
echo ""
echo "  f) Edit a file locally:"
echo "     nano My\ Contents/Data\ Structures/Arrays.md/index.md"
echo "     Change some text and save."
echo ""
echo "  g) Check status:"
echo "     npx tsx …/src/index.ts status"
echo "     Expected: Shows 'Arrays' as MODIFIED."
echo ""
echo "  h) Push changes:"
echo "     npx tsx …/src/index.ts push"
echo "     Expected: Uploads modified note to API."
echo ""
echo "  i) Verify in browser:"
echo "     Reload the Arrays note in the web app."
echo "     Expected: Shows the text you edited locally."
echo ""
echo "  j) Create a new note locally:"
echo "     mkdir -p My\ Contents/Data\ Structures/Graphs.md"
echo "     echo '# Graphs' > My\ Contents/Data\ Structures/Graphs.md/index.md"
echo "     npx tsx …/src/index.ts push"
echo "     Expected: New note appears in the sidebar."
echo ""

# ─── 9. Blob (image) upload ─────────────────────────────────────────────
echo "STEP 9 — Test inline image upload"
echo "───────────────────────────────────"
echo "  a) Open any note in the editor."
echo "  b) Paste an image from clipboard (Ctrl+V / Cmd+V)."
echo "     Expected: Image uploads and renders inline in the editor."
echo ""
echo "  c) Reload the page."
echo "     Expected: Image persists (loaded from cache)."
echo ""

# ─── 10. Content deletion ───────────────────────────────────────────────
echo "STEP 10 — Test content deletion"
echo "─────────────────────────────────"
echo "  a) Create a test note under any folder."
echo ""
echo "  b) Delete the note (right-click → Delete)."
echo "     Expected: Note disappears from sidebar."
echo ""
echo "  c) Create a note with a deck, then try to delete without cascade."
echo "     Expected: 409 error — 'use ?cascade=true'."
echo ""
echo "  d) Delete with cascade."
echo "     Expected: Note and deck both gone."
echo ""
echo "  e) Delete a folder with contents."
echo "     Expected: All descendants soft-deleted."
echo ""

# ─── 11. Smoke test summary ─────────────────────────────────────────────
echo "═══════════════════════════════════════════════════════════════"
echo "  Test Plan Complete"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "  If all steps above pass:"
echo "    ✅ Notes CRUD, auto-save, rename"
echo "    ✅ Folder CRUD, tags"
echo "    ✅ Deck & card CRUD"
echo "    ✅ Study mode (single deck + folder-level)"
echo "    ✅ Study result tracking"
echo "    ✅ CLI pull/push/status local workspace sync"
echo "    ✅ Inline image upload & persistence"
echo "    ✅ Content deletion (cascade)"
echo ""
echo "  Known pre-existing issues (not regressions):"
echo "    - TanStack Query console warnings in tests (harmless)"
echo "    - CSS.highlights not supported in jsdom (MDX editor test only)"
echo ""
